name: move commits

on:
  workflow_dispatch:
    inputs:
      branch_name:
        type: string
        default: release
      minor:
        type: string

jobs:
  get_tags:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}
          token: ${{ secrets.MY_PAT }}
          fetch-depth: 0

      - name: list all commits
        run: |
          git log --oneline | awk '{print $1}' > commits.txt

          cat commits.txt

          git branch

          echo START
          git config --global user.email "snsinahub@github.com"
          git config --global user.name "${{ github.actor }}"

          # Read the commit hashes from the file
          releaseMajor=1
          releaseMinor=${{ inputs.minor }}
          releasePatch=0
          release=$releaseMajor.$releaseMinor.$releasePatch
          touch reporel.txt
          ls -l
          while IFS= read -r commit; do
              
              echo RELEASE $release
              echo $commit
              # Check if the commit is part of the release branch
              git checkout main
              git cherry-pick $commit
              git checkout ${{ inputs.branch_name }}
              
              
              echo AFTER INCREMENT $release
              echo $release >> reporel.txt
              releaseMinor=$((releaseMinor + 1))
              release=$releaseMajor.$releaseMinor.$releasePatch
          done < commits.txt
          
          
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}

      
          
