name: move commits

on:
  workflow_dispatch:
    inputs:
      branch_name:
        type: string
        default: release

jobs:
  get_tags:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}
          token: ${{ secrets.MY_PAT }}

      - name: list all commits
        run: |
          git log --oneline | awk '{print $1}' 
          git log --oneline -1 | awk '{print $1}'
          git log
          git branch

          git checkout main
          git log --oneline -1 | awk '{print $1}'
          git log --oneline | awk '{print $1}'
          
