name: move commits

on:
  workflow_dispatch:
    inputs:
      branch_name:
        type: string
        default: release

jobs:
  get_tags:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}
          token: ${{ secrets.MY_PAT }}
          fetch-depth: 0

      - name: list all commits
        run: |
          git log --oneline | awk '{print $1}' > commits.txt

          cat commits.txt

          git checkout main

          # Read the commit hashes from the file
          while IFS= read -r commit; do
              # Check if the commit is part of the release branch
              if git branch -r --contains "$commit" | grep -q "origin/release"; then
                  # Check if the commit is not part of the main branch
                  if ! git branch -r --contains "$commit" | grep -q "origin/main"; then
                      echo "Moving commit $commit to main branch"
                      # Cherry-pick the commit to the main branch
                      git cherry-pick "$commit"
                  else
                      echo "Commit $commit is already part of the main branch"
                  fi
              else
                  echo "Commit $commit is not part of the release branch"
              fi
          done < commits.txt

      - name: list all commits main
        run: |
          git checkout main
          git log --oneline -1 | awk '{print $1}'
          git log --oneline | awk '{print $1}'
        continue-on-error: true
          
