name: move commits

on:
  workflow_dispatch:
    inputs:
      branch_name:
        type: string
        default: release

jobs:
  get_tags:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}
          token: ${{ secrets.MY_PAT }}
          fetch-depth: 0

      - name: list all commits
        run: |
          git log --oneline | awk '{print $1}' > commits.txt

          cat commits.txt
          

      - name: list all commits main
        run: |
          git checkout main
          git log --oneline -1 | awk '{print $1}'
          git log --oneline | awk '{print $1}'
        continue-on-error: true
          
