name: move commits

on:
  workflow_dispatch:
    inputs:
      branch_name:
        type: string
        default: release

jobs:
  get_tags:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}
          token: ${{ secrets.MY_PAT }}
          fetch-depth: 0

      - name: list all commits
        run: |
          git log --oneline | awk '{print $1}' > commits.txt

          cat commits.txt

          # git checkout main
          git config --global user.email "snsinahub@github.com"
          git config --global user.name "${{ github.actor }}"

          # Read the commit hashes from the file
          releaseMajor=1
          releaseMinor=20
          releasePatch=0
          release=$releaseMajor.$releaseMinor.$releasePatch
          touch commits.txt
          touch release.txt
          while IFS= read -r commit; do
              echo RELEASE $release
              # Check if the commit is part of the release branch
              git tag -a "v$release" $commit -m "$commit is part of the $release release"
              
              releaseMinor=$((releaseMinor + 1))
              release=$releaseMajor.$releaseMinor.$releasePatch
              echo AFTER INCREMENT $release
              echo $release >> release.txt
          done < commits.txt
          
          git push origin --tags

          echo "add to release"
          cat release.txt
          
          while IFS= read -r release; do
              gh release create "$release" --title "$release" --latest false
          done < release.txt
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}

      - name: list all commits main
        run: |
          git checkout main
          git log --oneline -1 | awk '{print $1}'
          git log --oneline | awk '{print $1}'
        continue-on-error: true
          
