name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
      update-release:
        type: choice
        default: false
        options:
          - 'true'
          - 'false'
      release-new-version:
        type: string
        default: ''
        required: false
      set-latest:
        type: choice
        default: false
        options:
          - 'true'
          - 'false'

    
     

jobs:
  update-create-release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: create a new release based on tag
        if: ${{ inputs.update-release == 'true' }}
        run: |
          gh release view ${{ inputs.tag }}
          gh release edit ${{ inputs.tag }} --title "${{ inputs.release-new-version }}"

        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}


      - name: modify a release
        if: ${{ inputs.update-release == 'false' }}
        run: |
          gh release create ${{ inputs.tag }} --title ${{ inputs.tag }} --latest false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
